Repository team-gingerbread/movie-cookie-fe, pull requests merged in 2023-12, with the labels that each got.

#10 Recommend api fetch 적용 & 기본 폴더, 파일 생성
  .vscode/settings.json
  index.html
  moviepick/index.html
  recommend/detail/index.html
  recommend/index.html
  recommend/list/index.html
  recommend/script/detail.js
  recommend/script/list.js
  recommend/script/recommend.js
  recommend/style/recommend.css
  script/common.js
  style/common.css
Labels: enhancement

#15 ✨ ADD: 공통 부분 js추가, base.css공통적용
  .vscode/settings.json
  index.html
  recommend/index.html
  recommend/script/recommend.js
  script/base.js
  script/common.js
  script/token.js
  script/url.js
  style/base.css
  style/common.css
Labels: enhancement

#17 💄 ADD: recommend입력창 js fetch, css
  base/base.css
  recommend/detail/index.html
  recommend/index.html
  recommend/script/recommend.js
  recommend/style/detail.css
  recommend/style/recommend.css
Labels: enhancement

#23 💄 UPDATE: 추천 입력창 UI 완료
  recommend/index.html
  recommend/script/recommend.js
  recommend/style/recommend.css
  style/base.css
Labels: enhancement

#25 💄UPDATE: 영화검색 및 정보조회 페이지 UI 수정, 페이지 이동 추가
  base/base.css
  movieinfo/detail/index.html
  movieinfo/index.html
  movieinfo/movieinfo.js
  movieinfo/script/detail.js
  movieinfo/script/index.js
  movieinfo/style/style.css
Labels: enhancement

#26 💄 ADD: 추천목록 페이지 완성
  recommend/index.html
  recommend/list/index.html
  recommend/script/list.js
  recommend/script/recommend.js
  recommend/style/recommend.css
Labels: enhancement

#29 Recommend 디테일페이지
  img/default.jpg
  recommend/detail/index.html
  recommend/index.html
  recommend/list/index.html
  recommend/script/detail.js
  recommend/script/list.js
  recommend/script/recommend.js
  recommend/style/detail.css
  recommend/style/recommend.css
Labels: enhancement

#32 ⚡️ UPDATE: 공통에 로그아웃 추가
  script/base.js
Labels: enhancement

#39 💄 ADD: 메인페이지 UI 완성
  base/base.css
  base/test.html
  img/background.jpg
  index.html
  style/base.css
  style/main.css
Labels: enhancement

#41 :zap:UPDATE: 좋아요 기능 및 한줄평 기능 추가, UI 수정
  .vscode/settings.json
  movieinfo/detail/index.html
  movieinfo/script/detail.js
  movieinfo/script/index.js
  movieinfo/style/style.css
  script/token.js
  style/base.css
Labels: enhancement

#43 ⚡️ UPDATE: 장르 리스트 동적요청 적용
  recommend/script/recommend.js
Labels: enhancement

#46 ⚡UPDATE: 코드 수정 및 프로필 영화 조회 기능 업데이트
  accounts/mypage-edit/index.html
  accounts/mypage/index.html
  accounts/script/login.js
  accounts/script/mypage-edit.js
  accounts/script/mypage.js
  accounts/script/signup.js
  accounts/style/mypage.css
  img/profile_basic.png
Labels: enhancement

#50 Movieinfo 토큰 부분 수정
  movieinfo/detail/index.html
  movieinfo/index.html
  movieinfo/script/detail.js
  script/token.js
Labels: enhancement

#52 💄UPDATE: footer고정 위한 main css 업데이트
  recommend/style/recommend.css
Labels: enhancement

#54 🚀 UPDATE: 배포용 백엔드 서버로 변경
  script/url.js
Labels: deploy

#56 🐛FIX: 댓글추가 버튼 기능 버그 해결
  community/detail/index.html
  community/script/detail.js
Labels: bug

#57 🚀 수정부분 다시 배포
  community/detail/index.html
  community/script/detail.js
Labels: deploy

#59 🐛BUG: 프로필 영화포스터 버그 수정
  accounts/script/mypage.js
  accounts/style/mypage.css
Labels: bug

#60 🚀수정사항 배포 반영
  accounts/script/mypage.js
  accounts/style/mypage.css
Labels: deploy

#65 🐛BUG: 프로필 변경 시 정보수정 안되는 오류 해결
  accounts/script/mypage-edit.js
  accounts/script/mypage.js
Labels: bug

#66 🚀 수정본 배포 반영
  README.md
  accounts/script/mypage-edit.js
  accounts/script/mypage.js
Labels: deploy

#68 ✨ADD: 커뮤니티 게시글 수정기능 구현
  community/detail/index.html
  community/script/detail.js
  community/script/write.js
  community/write/index.html
  script/url.js
Labels: enhancement

#69 🚀 수정본 배포 반영
  community/detail/index.html
  community/script/detail.js
  community/script/write.js
  community/write/index.html
Labels: deploy

#72 Community recomment
  community/detail/index.html
  community/script/detail.js
  community/script/write.js
  community/style/style.css
Labels: enhancement

#73 🚀 수정본 배포 반영
  community/detail/index.html
  community/script/detail.js
  community/script/write.js
  community/style/style.css
Labels: enhancement
